### ISSUE TITLE
SoapyUHD + CubicSDR + USRP B210: app does not work

### ISSUE THREAD

**Issue by dmitryelj** [pothosware/SoapyUHD#11]
Hi.

I have B210, cannot run it with CubicSDR app, that is using SoapyUHD driver. App can detect the receiver, but cannot get data stream from it.

System: Windows 10

Initial receiver settings:
![usrp_antennas](https://user-images.githubusercontent.com/18378056/31962530-1e121556-b8fe-11e7-88e6-088383444468.jpg)

CubicSDR log:
SDR enumerator starting.
SoapySDR init..
API Version: v0.6.0
ABI Version: v0.6
Install root: C:\Program Files\PothosSDR
Loading modules...
...
Available factories...airspy, audio, bladerf, hackrf, lime, miri, null, osmosdr, redpitaya, remote, rtlsdr, sdrplay, uhd
-- Loading firmware image: C:\Program Files\UHD\share\uhd\images\usrp_b200_fw.hex...
default_input = True
default_output = True
device_id = 0
...
driver = uhd
label = B210 3113F1D
name = MyB210
product = B210
serial = 3113F1D
type = b200
Make device 3
fpga_version=14.0
fw_version=8.0
mboard_id=B210
mboard_name=MyB210
mboard_serial=3113F1D
rx0_antenna=RX2
rx0_id=Unknown (0xffff)
rx0_serial=
rx0_subdev_name=FE-RX2
rx0_subdev_spec=A:A A:B
rx1_antenna=RX2
rx1_id=Unknown (0xffff)
rx1_serial=
rx1_subdev_name=FE-RX1
rx1_subdev_spec=A:A A:B
tx0_antenna=TX/RX
tx0_id=Unknown (0xffff)
tx0_serial=
tx0_subdev_name=FE-TX2
tx0_subdev_spec=A:A A:B
tx1_antenna=TX/RX
tx1_id=Unknown (0xffff)
tx1_serial=
tx1_subdev_name=FE-TX1
tx1_subdev_spec=A:A A:B

Reporting enumeration complete.
SDR enumerator done.
SDR thread starting.
device init()
**Device Stream MTU: 0** 
starting readLoop()
SDRThread::readStream(): 2. **SoapySDR read failed with code: -4**
SDRThread::readStream(): 3.1 iqDataOutQueue output queue is full, discard processing of the batch...
SDRThread::readStream(): 2. **SoapySDR read failed with code: -3**
SDRThread::readStream(): 3.1 iqDataOutQueue output queue is full, discard processing of the batch...
SDRThread::readStream(): 2. SoapySDR read failed with code: -4
SDRThread::readStream(): 3.1 iqDataOutQueue output queue is full, discard processing of the batch...
...
SDRThread::readStream(): 2. SoapySDR read failed with code: -3
SDRThread::readStream(): 3.1 iqDataOutQueue output queue is full, discard processing of the batch...
readLoop() ended.
device deinit()
SDR thread done.

As CubicSDR developers told, getStreamMTU cannot return 0, that may be an issue.

Other receivers (SDRPlay, RTL-SDR) works correct.

Can it be fixed? 
Thanks.

**PS**: I was able to launch the app with this settings:
![cubuc_uhd](https://user-images.githubusercontent.com/18378056/31964098-3ecda24c-b903-11e7-948d-8a8b1a153489.jpg)

What settings are optimal for USRP?

**Comment by guruofquality** [comment]
Is the rate testing app working for you? `SoapySDRUtil --args="driver=uhd" --rate=10e6 --channels=0 --direction=RX`

**Comment by dmitryelj** [comment]
Yes, it works.
![rate_test](https://user-images.githubusercontent.com/18378056/32068146-b78ee096-ba85-11e7-8b04-07d7c0309c85.jpg)

**Comment by dmitryelj** [comment]
All works in a last version.
