### ISSUE TITLE
Make failed on ubuntu 16.04

### ISSUE THREAD

**Issue by cn0xroot** [pothosware/SoapyUHD#12]
nice project for sdr.

```
init3@0xroot:~/sdr/SoapyUHD/build$ make
Scanning dependencies of target uhdSupport
[ 25%] Building CXX object CMakeFiles/uhdSupport.dir/SoapyUHDDevice.cpp.o
/home/init3/sdr/SoapyUHD/SoapyUHDDevice.cpp:17:33: fatal error: uhd/utils/log_add.hpp: No such file or directory
compilation terminated.
CMakeFiles/uhdSupport.dir/build.make:62: recipe for target 'CMakeFiles/uhdSupport.dir/SoapyUHDDevice.cpp.o' failed
make[2]: *** [CMakeFiles/uhdSupport.dir/SoapyUHDDevice.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/uhdSupport.dir/all' failed
make[1]: *** [CMakeFiles/uhdSupport.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

is there anybody has the same  Error?

**Comment by cn0xroot** [comment]
install uhd use `sudo apt-get install uhd-host` before,
`sudo apt-get remove uhd-host` ,then build uhd with source from https://github.com/EttusResearch/uhd.
it's fixed now

**Comment by guruofquality** [comment]
The uhd logging api changed between release and master branch, but the SoapyUHD should be backwards compatible as of this commit: https://github.com/pothosware/SoapyUHD/commit/dfdd0edc5225ca6edcd74012784cc63210c0b108

It uses the existence of this file: uhd/utils/msg.hpp to detect the API difference. Perhaps you had both source and debs installed and it confused the logic vs which headers were included?
