### ISSUE TITLE
Yocto/bitbake build fails.

### ISSUE THREAD

**Issue by 9600** [pothosware/SoapyUHD#14]
Able to build UHD and SoapySDR fine, but SoapyUHD fails with:

ERROR: QA Issue: soapyuhd: Files/directories were installed but not shipped in any package:
  /data/riscv-yocto/build/tmp/work/riscv64-poky-linux/soapyuhd/soapy-uhd-0.3.4+gitAUTOINC+55da7dad46-r0/recipe-sysroot/usr/lib/uhd/modules/libsoapySupport.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
soapyuhd: 1 installed and not shipped files. [installed-vs-shipped]

Tried setting FILES in the recipe, but didn't seem to help.

**Comment by guruofquality** [comment]
It does some non straitforward things with the uhd module. Not sure that this point for better or worse, I worked around it by overloading the UHD_ROOT passed to cmake to just be relative `-DUHD_ROOT=.`

Example: https://github.com/myriadrf/snapcraft-sandbox/blob/master/limesdr-osmotrx/snapcraft.yaml#L104

**Comment by 9600** [comment]
Many thanks, that did the trick!
