### ISSUE TITLE
hasGainMode() always returns false for UHD devices, even if AGC is supported

### ISSUE THREAD

**Issue by rlinus** [pothosware/SoapyUHD#15]
Because of a missing overload of SoapySDR::Device::hasGainMode() in SoapyUHDDevice.cpp, the method always returns false for UHD devices, even if AGC is supported. #

**Comment by guruofquality** [comment]
whats the uhd api for discovering this capability? its easy to add as long as there is a function to call

**Comment by ncorgan** [comment]
As of v3.14.1.1, UHD has a `multi_usrp::set_rx_agc` function (see [here](https://github.com/EttusResearch/uhd/blob/v3.14.1.1/host/include/uhd/usrp/multi_usrp.hpp#L1008)), but there is no API to query whether or not the functionality is supported for a given device.

This can be implemented by looking for a [specific entry](https://github.com/EttusResearch/uhd/blob/v3.14.1.1/host/lib/usrp/multi_usrp.cpp#L1595) in the property tree.

**Comment by guruofquality** [comment]
* https://github.com/pothosware/SoapyUHD/pull/24
