### ISSUE TITLE
SoapyUHD and XTRX

### ISSUE THREAD

**Issue by Dastgsm** [pothosware/SoapyUHD#23]
i would like to ask how good is the low latency hardware xtrx with the soapy? 

Chears,

**Comment by guruofquality** [comment]
Can you elaborate on the question? Are you concerned about how SoapyUHD wraps the streaming call?

**Comment by Dastgsm** [comment]
i ask sergei about : 
is it possible now to use soapyUHD with xtrx ?

and he tell me : Yes, its possible. However timed commands may not work as expected. It' in our TODO. What is timed commands?

**Comment by guruofquality** [comment]
Example: https://files.ettus.com/manual/page_sync.html#sync_phase_lo

**Comment by Dastgsm** [comment]
so the have timedcommands based , there are programming to do for front-end (SBX, UBX) because some option .. It says for example : 

    Phase synchronization with the UBX is only supported on the X3x0 Series
    Phase synchronization with the SBX works on both N2x0 and X3x0 Series
    There is a random phase offset between any two frontends
    This phase offset is different for different LO frequencies
    This phase offset remains constant after retuning
    This phase offset will drift over time due to thermal and other characteristics
    Periodic calibration will be necessary for phase-coherent applications


so for having good performance, the choise is to patch some program on the uhd indeed!!!

**Comment by Dastgsm** [comment]
And how about low latency? is the 8Gbps could be achieve with xtrx using soapyUHD?

**Comment by guruofquality** [comment]
> And how about low latency? is the 8Gbps could be achieve with xtrx using soapyUHD?

I don't really know the xtrx specs, but uhd's stream recv() function, Its just a thin wrapper around readStream(), please take a look at the code: https://github.com/pothosware/SoapyUHD/blob/master/UHDSoapyDevice.cpp#L565
