### ISSUE TITLE
Latest SoapyUHD build fails with boost errors

### ISSUE THREAD

**Issue by ghostop14** [pothosware/SoapyUHD#29]
This seems like a 'recent' issue, developed in the past 6 months.  Compiling now throws errrors similar to the following:
SoapyUHDDevice.cpp:68:13: error: ‘BOOST_FOREACH’ was not declared in this scope

Adding #include <boost/foreach.hpp> resolved this.

And a number of sptr conversion errors:
UHDSoapyDevice.cpp:153:65: error: conversion from ‘boost::shared_ptr<uhd::rx_streamer>’ to non-scalar type ‘uhd::rx_streamer::sptr {aka std::shared_ptr<uhd::rx_streamer>}’ requested
         uhd::rx_streamer::sptr stream = _rx_streamers[chan].lock();

UHDSoapyDevice.cpp:719:71: error: no match for ‘operator=’ (operand types are ‘std::map<long unsigned int, boost::weak_ptr<uhd::rx_streamer> >::mapped_type {aka boost::weak_ptr<uhd::rx_streamer>}’ and ‘uhd::rx_streamer::sptr {aka std::shared_ptr<uhd::rx_streamer>}’)
     BOOST_FOREACH(const size_t ch, args.channels) _rx_streamers[ch] = stream;

Build environment is Ubuntu 18.04 LTS 64-bit fully updated with the latest SoapySDR and SoapyUHD repo's.

**Comment by guruofquality** [comment]
I think they switched to c++11 so the typedefs are different Can you try the patch mentioned here? https://github.com/pothosware/SoapyUHD/issues/28 I didnt hear back on the other issue
