### ISSUE TITLE
SoapyUHD make errors at 100%, produces different errors

### ISSUE THREAD

**Issue by jth0078** [pothosware/SoapyUHD#45]
Log from SoapyUHD make

stormlabuser@stormlabuser-OptiPlex-7020:~/SoapyUHD/build$ make 
Scanning dependencies of target soapySupport
[ 20%] Building CXX object CMakeFiles/soapySupport.dir/UHDSoapyDevice.cpp.o
[ 40%] Linking CXX shared module libsoapySupport.so
[ 40%] Built target soapySupport
Scanning dependencies of target uhdSupport
[ 60%] Building CXX object CMakeFiles/uhdSupport.dir/SoapyUHDDevice.cpp.o
[ 80%] Building CXX object CMakeFiles/uhdSupport.dir/Version.cpp.o
[100%] Linking CXX shared module libuhdSupport.so
/usr/bin/ld: CMakeFiles/uhdSupport.dir/SoapyUHDDevice.cpp.o: in function `make_uhd(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)':
SoapyUHDDevice.cpp:(.text+0x1794): undefined reference to `uhd::msg::register_handler(void (* const&)(uhd::msg::type_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/uhdSupport.dir/build.make:104: libuhdSupport.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:133: CMakeFiles/uhdSupport.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Using any sort of UHD related component produces different errors including

stormlabuser@stormlabuser-OptiPlex-7020:~$ uhd_find_devices
Error: EnvironmentError: OSError: dlopen failed to load "/usr/local/lib/uhd/modules/libsoapySupport.so"
[INFO] [UHD] linux; GNU C++ version 9.3.0; Boost_107100; UHD_4.0.0.0-231-gb54fb54b
--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    serial: F3C22F
    addr: 192.168.10.2
    name: 
    type: usrp2

stormlabuser@stormlabuser-OptiPlex-7020:~$ SoapySDRUtil --probe="driver=uhd,type=usrp2"
######################################################
######################################################

Probe device driver=uhd,type=usrp2
[ERROR] SoapySDR::loadModule(/usr/local/lib/SoapySDR/modules0.8/libuhdSupport.so)
  dlopen() failed: libboost_date_time.so.1.65.1: cannot open shared object file: No such file or directory
Error probing device: SoapySDR::Device::make() no match

stormlabuser@stormlabuser-OptiPlex-7020:~$ SoapySDRUtil --info
######################################################
######################################################

Lib Version: v0.8.1-g5bcb611b
API Version: v0.8.0
ABI Version: v0.8
Install root: /usr/local
Search path:  /usr/local/lib/SoapySDR/modules0.8
Module found: /usr/local/lib/SoapySDR/modules0.8/libLMS7Support.so   (20.10.0-1480bfea)
Module found: /usr/local/lib/SoapySDR/modules0.8/libremoteSupport.so (0.6.0-c09b2f1)
Module found: /usr/local/lib/SoapySDR/modules0.8/libuhdSupport.so
  dlopen() failed: libboost_date_time.so.1.65.1: cannot open shared object file: No such file or directory
Available factories... lime, remote

Following advice from the Pothos google group,which was to add regex to BOOST_REQUIRED_COMPONENETS in cmake file does not fix it. I have purged and re-installed UHD, Boost, and SoapyUHD countless times. I was able to get it correctly running on a client PC following the exact same install steps. Could this be a problem with my SoapySDR install?

**Comment by jth0078** [comment]
Reinstalled SoapySDR this morning, make fail still occurs at libuhdSupport.so. All versions on the aforementioned second computer are the same as this one.

**Comment by guruofquality** [comment]
How did you install uhd? From package manager, from source, both?

are there different copies of uhd development files or runtime libraries sitting around. Like in /usr and /usr/local. Maybe that could cause some strangeness.

**Comment by jth0078** [comment]
I installed it from source, I went through and deleted every instance of UHD I could possibly find after removing SoapyUHD. Reinstalled UHD from source and SoapyUHD from source. Same issue.

**Comment by guruofquality** [comment]
The errors say `libboost_date_time.so.1.65.1` but the uhd_find_devices is printing boost `Boost_107100`. Not sure what os you have but ubuntu 20.04 comes with Boost_107100 aka 1.71. So SoapyUHD shouldnt even know about Boost 1.65. Maybe you have an old version of boost hanging around also on the system.

It might help to post the output from cmake and the output of `make VERBOSE=1` if you cant find the bad boost

**Comment by jth0078** [comment]
Seemed like two versions of boost were installed, formatting drive and reinstalling Linux eventually fixed this.
