### ISSUE TITLE
Update to work with latest uhd master logging API changes

### ISSUE THREAD

**Issue by cswiger** [pothosware/SoapyUHD#8]
Build fails against current uhd source with missing msg.hpp: 

src/SoapyUHD/SoapyUHDDevice.cpp:14:29: fatal error: uhd/utils/msg.hpp: No such file or directory

Have to go back to uhd 3.9.5 to get the missing /usr/local/include/uhd/utils/msg.hpp

**Comment by guruofquality** [comment]
It looks like this might be a recent issue introduced by master, but FWIW latest tag and maint appear to have the header: https://github.com/EttusResearch/uhd/blob/release_003_010_002_000/host/include/uhd/utils/msg.hpp

**Comment by guruofquality** [comment]
@cswiger Give it a try: https://github.com/pothosware/SoapyUHD/commit/dfdd0edc5225ca6edcd74012784cc63210c0b108

Master branch should now be compatible with master logging API changes and current releases. Code compiles, didnt test it on actual hardware yet.

**Comment by cswiger** [comment]
Thanks! Compiles yes, testing on hardware still in progress.

**Comment by guruofquality** [comment]
Closing. Will release either when the next uhd major release comes or sooner if there is a worthwhile change otherwise. Thanks for testing!
